version: '3'

services:

  php:
    container_name: php_server
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8000M
    build:
      context: ./docker/web
    volumes:
      - ./:/var/www/app
    depends_on:
      - db

  web:
    image: nginx:1.19-alpine
    container_name: server_web
    ports:
      - 300:80
    volumes:
      - ./:/var/www/app
      - ./docker/web/nginx/:/etc/nginx/conf.d/

  varnish:
    build: ./docker/web/varnish
    container_name: web_varnish
    links:
        - web
    ports:
      - 88:80
    depends_on:
      - web

  db:
    container_name: local_db
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=yourdb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
        PMA_HOST: local_db
    ports:
        - "8080:80"